# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "(^ansible/roles/)|(^.idea/)"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: detect-aws-credentials
        args:
          - "--allow-missing-credentials"

            #  - repo: https://github.com/ansible/ansible-lint
            #    rev: v4.3.3
            #    hooks:
            #      - id: ansible-lint

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.13.1
    hooks:
      - id: gitlint
        #  - repo: https://github.com/markdownlint/markdownlint
        #    rev: v0.8.0
        #    hooks:
        #      - id: markdownlint

  - repo: https://github.com/prettier/prettier
    rev: "2.1.1" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
