- hosts: localhost
  roles:
    - name: "install intellij"
      role: gantsign.intellij
      intellij_edition: ultimate
      intellij_version: '2020.3.2'
      users:
        - username: "{{ ansible_user_id }}"
          intellij_codestyles:
            - name: java-google
              url: https://raw.githubusercontent.com/google/styleguide/gh-pages/intellij-java-google-style.xml
          intellij_default_codestyle: java-google
          intellij_disabled_plugins:
            - CVS
            - com.intellij.uiDesigner
            - org.jetbrains.android
            - TestNG-J
            - DevKit
