= B-F-W
Richard Attermeyer <richard.attermeyer@gmail.com>
:compat-mode!:
:icons: font
:sectnums:
:toc:


B-F-W (Bootstrap for Workstation) is a project to quickly setup a workding Linux desktop (development) environment on Fedora and Ubuntu.

== Components installed

=== Command line tools

The following command line tools are installed (in addition to what the different distributions provide per default).

==== Ag

https://github.com/ggreer/the_silver_searcher[Ag] is a code searching tool. It allows to easily "grep" through your project directory without using a `find` and `grep` combination.

Beside this it
* ignores file patterns for `.gitignore`
* you can ignore files by adding the pattern to a `.ignore` file.

[source,bash]
....
➜  ods-core git:(master) ag --stats "PROXY_TRIGGER_SECRET"
create-projects/ocp-config/cd-jenkins/cd-jenkins-webhook-proxy.yml
17:- name: PROXY_TRIGGER_SECRET_B64
121:    trigger-secret: ${PROXY_TRIGGER_SECRET_B64}

create-projects/create-cd-jenkins.sh
87:  "--param=PROXY_TRIGGER_SECRET_B64=${PIPELINE_TRIGGER_SECRET}" \

tests/create-projects/jenkinsfile_test.go
161:		fmt.Sprintf("--param=%s", fmt.Sprintf("PROXY_TRIGGER_SECRET_B64=%s", secret))}, dir, []string{})
4 matches
3 files contained matches
374 files searched
561279 bytes searched
0.025193 seconds
➜  ods-core git:(master)
....

==== bat

https://github.com/sharkdp/bat[`bat`] is the better cat.
Use it wherever you would use cat, especially if you are working on a source file.
Bat supports:

* Syntax highlighting
* git integration (showing modifications)
* showing non printable characters (using `-A / --show-all`)
* automatic paging

==== httpie
https://httpie.org/[HTTPie] is a command line HTTP client with UI, JSON support, syntax highlighting, and more.
Instead of using `wget` or `curl` especially when dealing with REST services, use httpie instead.

==== jq
https://stedolan.github.io/jq/[jq] is a handy tool to slice, filter, transform JSON data.

==== tree
https://wiki.ubuntuusers.de/tree/[tree] is a simple Linux utility to display the dirctory structure as a tree.

[source,bash]
....
➜  ~ tree -L 1 -d /etc/apt
/etc/apt
├── apt.conf.d
├── auth.conf.d
├── preferences.d
├── sources.list.d
└── trusted.gpg.d
....

=== pgcli
Because the default database in my projects is Postgres, it is always a good idea to have a postgresl client at your fingertips.
https://www.pgcli.com/[Pgcli] is a command line interface for Postgres with auto-completion and syntax highlighting.
We also provide a GUI tool (pgadmin4) in this setup.

=== byoby / tmux
https://byobu.org/[Byobu] includes enhanced profiles and convenient keybindings, configuration utilities and toggle-able system status notification for https://github.com/tmux/tmux/wiki[tmux].
You can simply use byobu wherever you would use tmux.


* add-gitignore (open)
* aws-cli (open)
* azure-cli (open)
* onedrive client business (open)
* rclone
* fzf

* how2 (open)
* dracula theme for zsh (open)
* fzf (open)
* htop (open)
* mtr (instead of tracerout, open)
* aria2 (open)
* asciinema (open)

=== Backup

* borgbackup (open, cmdline) / vorta
* backintime (open, GUI)
* timeshift

=== Programming Languages

* sdkman
* rvm
* nvm
* java (11)
* python3
* gcc-c++
* golang

Beside installing some programming languages and management tools, the idea on my desktop is that
code should always be checked in in an opinionated formatted way. And this should be done without the developer to care about.
We also often face the problem that developers use different platforms (Windows, Linux, MacOS) and we should try to minimize issues
when working with wrong line endings.

Furthermore, we would like to ignore certain (mostly IDE related) files from being commited to git history.

To achieve this, we follow the follogin solution strategy

.Solution Strategy
|===
| Quality Attribute / Scenario | Solution Strategy

| Consistent formatting of source code
| Using [Prettier] and installing extensions for IDEs (VS Code, VIM). Install git `pre-commit` hook manager and configure it for your project.

| Consistent Look and feel
| Using dracula plugins for different IDEs (VS Code, VIM, IntelliJ)
|===

=== Additional GUI programs
(open)

==== Password Manager: KeypassXC (open)
KeypassXC is a password manager. It is installed and started directly when you log in.
To profit, install the firefox and chromium extensions (open).

* chromium + extensions
* Nextcloud-client
* pgadmin4 (open)

=== DevOps (misc)

* vagrant
* Virtualbox
* libvirt
* virt-manager
* ansible
* ansible-lint

=== Docker and the like

* docker
* podman
* minikube

=== Editors and Extensions

* fira-code
* vim + vundle + extensions
* vscode + extensions
* intellij

=== git and configurations

* git
* git-config
* git-credentials
* global git ignores
* pre-commit
* tig
* meld

=== Shell and activated plugins

Because the shell is the most important tool for a real hacker to interact with, it is especially important that we use
the best tools available.

Therefore we install https://github.com/ohmyzsh/ohmyzsh[`oh-my-zsh`] as the default shell for the user.
Oh-my-zsh has lots of plugins that make it easy to customize your shell to your liking.

We support a lot of the installed tools with oh-my-zsh plugins.

.Plugins
|===
|Plugin | why included

|docker
|Auto-complete argumeents and options

|kubectl
|Autocompletion

|oc
|Autocompletion for OpenShift cmd line interface

|mvn
|Standard build tool for Java projects

|gradle
|autocompletion of task names and option switches

|npm
|autocompletion for npm

|nvm
|to support the node version manager

|https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#vscode[vscode]
|Visual Studio code extra commands


|httpie
|Completion for httpie

|ng
|Completion for `angular-cli`

|vagrant
|autocompletion for Bagrant commands, task names, box names

|===


* powerline


=== Additional GUI programs
